services:
  db:
    image: postgres:15
    container_name: dashflow-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dashflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  ollama:
    image: ollama/ollama:latest
    container_name: dashflow-ollama
    restart: always
    ports:
      - "11434:11434"
    extra_hosts:
      - "registry.ollama.ai:104.21.75.227"
    volumes:
      - C:/Users/sreep/.ollama:/root/.ollama

volumes:
  pgdata:
  ollama_data:
